GET http://127.0.0.1:8000/images
Accept: application/json

###

POST http://127.0.0.1:8000/images
Accept: application/json

--boundary
Content-Disposition: form-data; name="file"; filename="test-image.jpg"
Content-Type: image/jpeg

< ./path/to/your/test-image.jpg
--boundary--

###